// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_MiseJoueur")]
public partial class TblMiseJoueur
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ID_StatutMise")]
    public short IdStatutMise { get; set; }

    [Column("ID_Utilisateur")]
    public long IdUtilisateur { get; set; }

    [Column("ID_Tirage")]
    public long IdTirage { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MisePremierNumeroGagnant { get; set; }

    public long PremierNumeroGagnant { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MiseDeuxiemeNumeroGagnant { get; set; }

    public long DeuxiemeNumeroGagnant { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MiseTroisiemeNumeroGagnant { get; set; }

    public long TroisiemeNumeroGagnant { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateCreated { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal MontantGagne { get; set; }

    [ForeignKey("IdTirage")]
    //[InverseProperty("TblMiseJoueurs")]
    public virtual TblTirage IdTirageNavigation { get; set; }

    [ForeignKey("IdUtilisateur")]
    //[InverseProperty("TblMiseJoueurs")]
    public virtual TblUtilisateur IdUtilisateurNavigation { get; set; }

    //[InverseProperty("IdMiseJoueurNavigation")]
    public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();
}