// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_Profession")]
[Index("Libelle", Name = "IX_Tbl_Profession", IsUnique = true)]
public partial class TblProfession
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Libelle { get; set; }

    public DateOnly DateCreated { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    public DateOnly? DateModif { get; set; }

    [StringLength(50)]
    public string ModifBy { get; set; }
}