// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_RefProfilUtilisateur")]
[Index("Libelle", Name = "IX_Tbl_RefProfilUtilisateur", IsUnique = true)]
public partial class TblRefProfilUtilisateur
{
    [Key]
    [Column("ID")]
    public short Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Libelle { get; set; }

    //[InverseProperty("IdProfilNavigation")]
    public virtual ICollection<TblUtilisateur> TblUtilisateurs { get; set; } = new List<TblUtilisateur>();
}