// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_RefStatutTirage")]
[Index("Libelle", Name = "IX_Tbl_RefStatutTirage", IsUnique = true)]
public partial class TblRefStatutTirage
{
    [Key]
    [Column("ID")]
    public short Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Libelle { get; set; }

    //[InverseProperty("IdStatutTirageNavigation")]
    public virtual ICollection<TblTirage> TblTirages { get; set; } = new List<TblTirage>();
}