// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_RefSensTransaction")]
[Index("Libelle", Name = "IX_Tbl_RefSensTransaction", IsUnique = true)]
public partial class TblRefSensTransaction
{
    [Key]
    [Column("ID")]
    public short Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Libelle { get; set; }

    //[InverseProperty("IdSensTransactionNavigation")]
    public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();
}