// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_Transaction")]
public partial class TblTransaction
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ID_SensTransaction")]
    public short IdSensTransaction { get; set; }

    [Column("ID_TypeTransaction")]
    public long IdTypeTransaction { get; set; }

    [Column("ID_MiseJoueur")]
    public long? IdMiseJoueur { get; set; }

    [Column("ID_Utilisateur")]
    public long IdUtilisateur { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateTransaction { get; set; }

    [Required]
    [StringLength(100)]
    public string Description { get; set; }

    [Column(TypeName = "decimal(18, 2)")]
    public decimal Montant { get; set; }

    public DateOnly DateCreated { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [ForeignKey("IdMiseJoueur")]
    //[InverseProperty("TblTransactions")]
    public virtual TblMiseJoueur IdMiseJoueurNavigation { get; set; }

    [ForeignKey("IdSensTransaction")]
    //[InverseProperty("TblTransactions")]
    public virtual TblRefSensTransaction IdSensTransactionNavigation { get; set; }

    [ForeignKey("IdUtilisateur")]
    //[InverseProperty("TblTransactions")]
    public virtual TblUtilisateur IdUtilisateurNavigation { get; set; }
}