// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_Tirage")]
public partial class TblTirage
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ID_StatutTirage")]
    public short IdStatutTirage { get; set; }

    public short CoefficientPremierNumeroGagnant { get; set; }

    public int PremierNumeroGagnant { get; set; }

    public short CoefficientDeuxiemeNumeroGagnant { get; set; }

    public int SecondNumeroGagnant { get; set; }

    public short CoefficientTroisiemeNumeroGagnant { get; set; }

    public int TroisiemeNumeroGagnant { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateCreation { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateModif { get; set; }

    [StringLength(50)]
    public string ModifBy { get; set; }

    [ForeignKey("IdStatutTirage")]
    //[InverseProperty("TblTirages")]
    public virtual TblRefStatutTirage IdStatutTirageNavigation { get; set; }

    //[InverseProperty("IdTirageNavigation")]
    public virtual ICollection<TblMiseJoueur> TblMiseJoueurs { get; set; } = new List<TblMiseJoueur>();
}