// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BorletteRepository.DAOEFC.EFC;

[Table("Tbl_Utilisateur")]
[Index("CodeUtilisateur", Name = "IX_Tbl_Utilisateur", IsUnique = true)]
public partial class TblUtilisateur
{
    [Key]
    [Column("ID")]
    public long Id { get; set; }

    [Column("ID_Profession")]
    public long IdProfession { get; set; }

    [Column("ID_Statut")]
    public short IdStatut { get; set; }

    [Column("ID_Profil")]
    public short IdProfil { get; set; }

    [Required]
    [StringLength(20)]
    public string CodeUtilisateur { get; set; }

    public DateOnly DateNaissance { get; set; }

    [Required]
    [StringLength(100)]
    public string Email { get; set; }

    [Required]
    [StringLength(20)]
    public string Nif { get; set; }

    [Required]
    [StringLength(50)]
    public string Nom { get; set; }

    [Required]
    [StringLength(50)]
    public string Prenom { get; set; }

    [Required]
    [StringLength(1)]
    public string Sexe { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateCreated { get; set; }

    [Required]
    [StringLength(50)]
    public string CreatedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? DateModif { get; set; }

    [StringLength(50)]
    public string ModifBy { get; set; }

    [Required]
    [StringLength(20)]
    public string Password { get; set; }

    [ForeignKey("IdProfil")]
    //[InverseProperty("TblUtilisateurs")]
    public virtual TblRefProfilUtilisateur IdProfilNavigation { get; set; }

    [ForeignKey("IdStatut")]
    //[InverseProperty("TblUtilisateurs")]
    public virtual TblRefStatutUtilisateur IdStatutNavigation { get; set; }

    //[InverseProperty("IdUtilisateurNavigation")]
    public virtual ICollection<TblMiseJoueur> TblMiseJoueurs { get; set; } = new List<TblMiseJoueur>();

    //[InverseProperty("IdUtilisateurNavigation")]
    public virtual ICollection<TblTransaction> TblTransactions { get; set; } = new List<TblTransaction>();
}